version: '3.7'

services:
  bot:
    build:
      context: ./src/bot
      dockerfile: bot.dockerfile
    restart: on-failure
    environment:
      REDIS_HOST: redis
      POSTGRES_SERVER: db
    volumes:
      - ./logs:/bot/logs
      - ./locales:/bot/locales
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:10.13
    restart: on-failure
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  redis:
    image: redis
    restart: on-failure
    volumes:
      - ./data/redis:/data
  pgadmin:
    image: dpage/pgadmin4:6.0
    ports:
      - "9999:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: test@test.com
      PGADMIN_DEFAULT_PASSWORD: test